name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: '9.13.2'
          run_install: false

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Create folder and copy files
        run: |
          mkdir -p ollama-transcript-processor
          cp main.js manifest.json styles.css versions.json ollama-transcript-processor/
          zip -r ollama-transcript-processor.zip ollama-transcript-processor

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
          files: |
            ollama-transcript-processor.zip
